### ISSUE TITLE
ERROR incompatible data file 

### ISSUE THREAD

**Issue by AmitMY** [ranyadshalom/seinfeld_laugh_corpus#1]
Thanks for this cool corpus.

I ran:
```sh
pip3 install seinfeld_laugh_corpus
```

and then:
```py
from seinfeld_laugh_corpus import corpus
seinfeld = corpus.load()
```

The corpus loading line fails fataly:
> ERROR incompatible data file 'Seinfeld.S08E21.The.Muffin.Tops.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E15.The.Visa.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E12.The.Money.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E11.The.Dealership.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E08.The.Barber.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E03.The.Maestro.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E09.The.Opera.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E10.The.Andrea.Doria.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E01.The.Mango.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E13.The.Scofflaw.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E20.The.Calzone.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E19.The.Yada.Yada.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E17.The.Wife.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E21.The.Smelly.Car.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E06.The.Lip.Reader.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E17.The.Outing.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E10.The.Gum.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E13.The.Dinner.Party.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E04.The.Wink.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E17.The.Doll.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E14.The.Marine.Biologist.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E02.The.Soul.Mate.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E23.The.Face.Painter.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E17.The.Kiss.Hello.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E03.The.Glasses.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E18.The.Old.Man.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E12.The.Reverse.Peephole.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E06.The.Gymnast.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E08.The.Pool.Guy.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E07.The.Secret.Code.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E10.The.Cigar.Store.Indian.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E16.The.Stand-In.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E14.The.Strongbox.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E14.The.Van.Buren.Boys.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E06.The.Soup.Nazi.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E22.The.Diplomats.Club.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E17.The.Bookstore.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E08.The.Cheever.Letters.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E03.The.Serenity.Now.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E20.The.Junior.Mint.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E21.The.Fusilli.Jerry.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E13.The.Cartoon.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E20.The.Doodle.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E12.The.Caddy.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E05.The.Hot.Tub.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E16.The.Shoes.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E15.The.Susie.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E12.The.Label.Maker.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E09.The.Sponge.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E20.The.Fire.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E13.The.Comeback.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E07.The.Soup.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E09.The.Apology.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E01.The.Foundation.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E04.The.Little.Kicks.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E19.The.Maid.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E15.The.Wizard.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E06.The.Watch.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E07.The.Bubble.Boy.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E18.The.Frogger.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E04.The.Blood.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E09.The.Masseuse.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E07.The.Non-Fat.Yogurt.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E12.The.Airport.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E04.The.Sniffing.Accountant.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E21.The.Hamptons.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E19.The.Jimmy.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E08.The.Chicken.Roaster.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E06.The.Merv.Griffin.Show.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E02.The.Voice.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E09.The.Abstinence.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E18.The.Nap.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E06.The.Fatigues.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E01.The.Engagement.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E11.The.Little.Jerry.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E11.The.Conversion.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E02.The.Postponement.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E10.The.Virgin.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E05.The.Junk.Mail.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E10.The.Strike.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E05.The.Package.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E20.The.Millennium.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E13.The.Pick.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E08.The.Mom.and.Pop.Store.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E15.The.Pie.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S07E16.The.Shower.Head.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E12.The.Stall.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S09E16.The.Burning.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E19.The.Implant.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E05.The.Bris.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S05E02.The.Puffy.Shirt.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E22.The.Handicap.Spot.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S04E11.The.Contest.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S08E03.The.Bizarro.Jerry.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E09.The.Secretary.merged'. Skipped. ('errors' is an invalid keyword argument for this function)
> ERROR incompatible data file 'Seinfeld.S06E18.The.Doorman.merged'. Skipped. ('errors' is an invalid keyword argument for this function)

**Comment by ranyadshalom** [comment]
Hi Amit,
I'm glad you liked the corpus.
You will get this error if you tried running this code on Python 2. Are you sure you're using Python 3 as instructed?

**Comment by AmitMY** [comment]
Thanks. You are right, I got my environments confused.
Using python 3 it works
